### PR TITLE
Update documentation

### LINKED ISSUE #2: Status pending is allowed for import.

### LINKED ISSUE #3: Update documentation, warning about spreadsheet software.
LOVD 2.0 manual heeft een waarschuwing over Spreadsheet software, die moet ook in de LOVD 3.0 handleiding komen.

### LINKED ISSUE #4: Create chapters on public usage, views, search data, meaning of the tabs.
(Ivo) While everything should be explained *somewhere* and arguably this information is not technical so could perhaps be separated from the manual, I prefer the idea of having one single document (the manual) with all the info, and we could create a "quick-reference", "cheatsheet" kind of document, with the most important information for somebody new to the LOVD interface. Information to go into there:
- The tabs, and what they show
- The various variant views (unique, all variants, full data view)
- How to sort, how to search
- Search filter examples
- More?
I believe we can fit this in one page, with a screenshot and areas of interest indicated with a box or a neat line. We would need to look at how to design this, before starting to implement this.

### LINKED ISSUE #5: Documentation about the new unique variant view.

### PR DESCRIPTION
**Pull request by dasscheman**
closes #2, closes #3, closes #4 and closes #5

### CODE REVIEW

**Comment by martijnvermaat** [comment]
Hi @LOVDnl/lovd-team, just a heads-up from the other side :beer: 

Here we have the situation of a merge conflict. You cannot fix this in the GitHub UI. Two ways to fix it from the command line:

1. Merge `Update_documentation` while resolving conflicts:

        git checkout master
        git pull
        git merge origin/Update_documentation
        # Edit src/class/template.php and save as you want it to be.
        git add src/class/template.php
        git commit
        git push

2. Rebase `Update_documentation` on current master while resolving conflicts and update this PR:

        git checkout master
        git pull
        git checkout Update_documentation
        git rebase master
        # Edit src/class/template.php and save as you want it to be.
        git add src/class/template.php
        git rebase --continue
        git push origin Update_documentation -f

    Now you can accept this PR from the GitHub UI.

I usually prefer the second way, but admit the rebase command might be one of the more advanced.

**Comment by martijnvermaat** [comment]
Oh, I now see there's another thing going on here. My comment above applies to #1.

This branch includes both the commit from #1 and the docs update. That is because this `Update_documentation` branch was started from the `View_page_titles` branch instead of from the `master` branch. I think the best way to proceed is to first merge #1 following the first way described above and then this PR.

**Comment by dasscheman** [comment]
Creating a `Update_documentation` branch from the `View_page_titles` was done on purpose. Because in the branch `View_page_titles` I changed some titles and when these are changed in the review, the documentation has to be changed as well. So when `View_page_titles` is merged, this branch can be merged as well.

**Comment by ifokkema** [comment]
Thanks @martijnvermaat , I managed to merge the branch without issues. I had to scratch my head for what to do with the binary PDF file, but obviously regenerating it from the merged manual.tex was the only way to go.

**Comment by martijnvermaat** [comment]
I would actually suggest not to have the PDF in Git, but that's another matter :smile:

**Comment by ifokkema** [comment]
I see your point, but I do think a GitHub download should be complete, and therefore would need to have the PDF, too... Otherwise they would need to generate it...
Actually reminds me... @dasscheman , could you re-generate the HTML file please, and push it into master? That conversion program doesn't work on my computer...

**Pull request merged**
