### PR TITLE
Import

### LINKED ISSUE #6: Mesage: Please select a valid entry from the 'refseq_genomic' selection box should not be displayed.
In object_genes the variable $aSelectRefseqGenomic is not set properly. It is only filled with the first NC that is found, hereafter the caching in the getForm function  (if (!empty($this->aFormData)) { return parent::getForm(); }) cause that this variable is not further completed.

### PR DESCRIPTION
**Pull request by dasscheman**
Trello tasks https://trello.com/c/G87b1p0c and https://trello.com/c/x5HLAegf
See commits for explanation. 

**edit by mkroon1:**
Fixes #6 (but not #7)

### CODE REVIEW

**Comment by ifokkema** [comment]
Hello,
I made some comments on the commits, could you please attend to those, if you have time?
The second trello card (https://trello.com/c/x5HLAegf) doesn't actually seem to be included? Although one of the issues doesn't seem to happen anymore (not complaining if the individual isn't found), that also doesn't happen in master anymore, and the individualids are still not forced to integers. Try this import file, so you see what I mean:
```
### LOVD-version 3000-14c ### Full data download ### To import, do not remove or alter this header ###
# charset = UTF-8

## Diseases ## Do not remove or alter this header ##
## Individuals ## Do not remove or alter this header ##
"{{id}}"
"asdf"

## Individuals_To_Diseases ## Do not remove or alter this header ##
## Count = 16
"{{individualid}}"	"{{diseaseid}}"
"asdf"	"00001"
```
The "id" field is checked properly and complains that "asdf" is not a number, but LOVD does not complain about "individualid" is not numeric.

**Comment by dasscheman** [comment]
Ah now I see what you mean. I thought it was about the first commit; integers checked as strings. 
I will have a look.

**Comment by dasscheman** [comment]
It seems to be a more general problem, because for transcriptid, screeningid, variantid this also happens. Changing diseaseid to 'asdf' gives an mysql_error. I'm not sure if you want this checked in objects, or in the import.

**Comment by ifokkema** [comment]
OK, I'll take over and take a look at it later, then :)

**Pull request merged**
