### PR TITLE
Variant count in transcript viewlist takes status and ownership into account.

### PR DESCRIPTION
**Pull request by mkroon1**
Transcript viewlists on pages transcript/geneID and genes/geneID now
shows a variant count depending on the user level. Specifically, a user
with a level lower than collaborator will see the count for variants
with status public, plus variants that are either owned or created by
him.

### CODE REVIEW

**Comment by mkroon1** [comment]
Please wait before merging, I've forgotten to update the changelog.

**Comment by mkroon1** [comment]
Now it should be ready to merge.

**Comment by ifokkema** [comment]
Thanks! I had to make some changes to fix some problems, see 987b1c6 for the fixes.
I'm also wondering why the branch has conflicts with master, because the branch was created today, right? Maybe you forgot a `git fetch` before branching?

**Comment by mkroon1** [comment]
Thanks, I missed transcripts without variants in my train of thought.

> I'm also wondering why the branch has conflicts with master, because the branch was created today, right? Maybe you forgot a `git fetch` before branching?

According to the network graph I made the branch on the 9th, in the mean time you merged [another branch](https://github.com/LOVDnl/LOVD3/commit/b4ff94c70d75b04a71594e2f2eb43ffb4f9119b5) which may have caused it.

**Pull request merged**
